#!/bin/bash

# Helpers
alias cc="clear"
alias x="exit"
alias ":q"="exit"
alias vimrc="vim ~/.vimrc"
alias lg="lazygit"
alias sc="./vendor/bin/scratch" # Ebook generator package

# JS
alias watch="npm run watch"

# Git
alias wip="git add . && git commit -m 'WIP'"
alias push="git push"
alias gl="git log --graph --abbrev-commit --decorate --date=relative "
alias pull="git pull origin "
alias push="git push origin "
alias wpush="git add . && git commit -m 'WIP' && git push"
alias nah="git reset --hard && git clean -df"

# PHP
alias dump="composer dump-autoload -o"
alias ci="composer install"
# alias p="./vendor/bin/phpunit"
# alias pf="./vendor/bin/phpunit --filter "
alias p="./vendor/bin/pest "
alias pf="./vendor/bin/pest --filter"
alias pint="./vendor/bin/pint "

# Laravel
alias a="php artisan "
alias migrate="php artisan migrate"
alias fresh="php artisan migrate:fresh"
alias seed="php artisan db:seed"
alias sail="./vendor/bin/sail "
alias pstorm="open -a PhpStorm "
alias wstorm="open -a WebStorm "

# open vim/nvim as quickly as possible
alias v="vim "
alias n="nvim "
alias nv="nvim "
alias nvi="nvim "

# docker
alias d="docker "
alias dc="docker-compose "
alias dcu="docker-compose up"
alias dcd="docker-compose down"
alias dps="docker ps"

# Opens database in applications like TablePlus
# Example 1: `db` command will check env file in its directory and grab env variables and will open that database
# Example 2: `db test` command will open test database
db() {
  if [ $# -eq 0 ]; then
    [ ! -f .env ] && {
      echo "No .env file found."
      return 0
    }

    DB_HOST=$(grep DB_HOST .env | grep -v -e '^\s*#' | cut -d '=' -f 2-)
    DB_PORT=$(grep DB_PORT .env | grep -v -e '^\s*#' | cut -d '=' -f 2-)
    DB_DATABASE=$(grep DB_DATABASE .env | grep -v -e '^\s*#' | cut -d '=' -f 2-)
    DB_USERNAME=$(grep DB_USERNAME .env | grep -v -e '^\s*#' | cut -d '=' -f 2-)
    DB_PASSWORD=$(grep DB_PASSWORD .env | grep -v -e '^\s*#' | cut -d '=' -f 2-)

    DB_URL="mysql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}"
  fi

  if [ $# -eq 1 ]; then
    DB_URL="mysql://127.0.0.1/$1"
  fi

  open $DB_URL
}
